export const elements={earth:{name:'Earth',icon:'◆',color:'#a38c57',bg:'#e9dfc8',value:3,cost:60,interval:3},wind:{name:'Wind',icon:'≋',color:'#80a49a',bg:'#e0e9e5',value:3,cost:60,interval:3},fire:{name:'Fire',icon:'♨',color:'#d58e59',bg:'#f6e1ce',value:4,cost:80,interval:4},water:{name:'Water',icon:'◕',color:'#719bb1',bg:'#dce8ed',value:4,cost:80,interval:4},lava:{name:'Lava',icon:'◒',color:'#d47b42',bg:'#f2d2b9',value:18,cost:220,interval:5},steam:{name:'Steam',icon:'♧',color:'#9aaba0',bg:'#e2e9df',value:20,cost:250,interval:5},dust:{name:'Dust',icon:'✧',color:'#b8a678',bg:'#eee6d1',value:14,cost:180,interval:4},clay:{name:'Clay',icon:'▰',color:'#b98a77',bg:'#efddd2',value:16,cost:200,interval:5},stone:{name:'Stone',icon:'⬟',color:'#8c9280',bg:'#e0e2d6',value:45,cost:550,interval:7},glass:{name:'Glass',icon:'◇',color:'#7ba6a8',bg:'#dfefea',value:90,cost:1000,interval:9}};
export const recipes={lava:['earth','fire'],steam:['water','fire'],dust:['earth','wind'],clay:['earth','water'],stone:['lava','water'],glass:['dust','fire']};
export const dirs=[[1,0],[0,1],[-1,0],[0,-1]];
export const key=(x,y)=>`${x},${y}`;
export function fresh(){let s={money:850,earned:0,sold:0,unlocked:['earth','wind','fire','water','lava'],blocks:{},particles:[],clock:0};const add=(x,y,type,el,dir=0)=>s.blocks[key(x,y)]={x,y,type,el,dir,timer:0,stock:{}};add(2,3,'producer','earth');add(3,3,'belt');add(4,3,'belt');add(5,3,'factory','lava');add(5,6,'producer','fire',3);add(5,5,'belt',null,3);add(5,4,'belt',null,3);add(6,3,'belt');add(7,3,'belt');add(8,3,'seller');return s;}
export function price(type,el){return type==='producer'?elements[el].cost:type==='factory'?150:type==='seller'?100:10;}
export function place(s,x,y,type,el,dir=0){if(s.blocks[key(x,y)])return 'This tile is already occupied.';if(type==='producer'&&!s.unlocked.includes(el))return 'Build a factory for this element first.';const cost=price(type,el);if(s.money<cost)return 'Not enough money. Let your factory earn a little more.';s.money-=cost;s.blocks[key(x,y)]={x,y,type,el,dir,timer:0,stock:{}};if(type==='factory'&&!s.unlocked.includes(el))s.unlocked.push(el);return null;}
export function remove(s,x,y){let b=s.blocks[key(x,y)];if(!b)return false;s.money+=Math.floor(price(b.type,b.el)*.5);delete s.blocks[key(x,y)];return true;}
function output(s,b,el){if(s.particles.filter(p=>p.x===b.x&&p.y===b.y).length>=4)return false;s.particles.push({x:b.x,y:b.y,fromX:b.x,fromY:b.y,el,progress:0,dir:b.dir});return true;}
export function tick(s,dt){s.clock+=dt;for(const b of Object.values(s.blocks)){b.timer+=dt;if(b.type==='producer'&&b.timer>=elements[b.el].interval){if(output(s,b,b.el))b.timer=0;}if(b.type==='factory'&&b.timer>=2&&recipes[b.el].every(el=>(b.stock[el]||0)>0)){if(output(s,b,b.el)){recipes[b.el].forEach(el=>b.stock[el]--);b.timer=0;}}}
const alive=[];for(const p of s.particles){p.progress+=dt*1.7;if(p.progress<1){alive.push(p);continue;}const b=s.blocks[key(p.x,p.y)];const dir=b?.dir??p.dir;const [dx,dy]=dirs[dir];const nx=p.x+dx,ny=p.y+dy;const dest=s.blocks[key(nx,ny)];if(dest?.type==='seller'){s.money+=elements[p.el].value;s.earned+=elements[p.el].value;s.sold++;continue;}if(dest?.type==='factory'&&recipes[dest.el].includes(p.el)&&(dest.stock[p.el]||0)<20){dest.stock[p.el]=(dest.stock[p.el]||0)+1;continue;}if(dest?.type==='belt'&&!s.particles.some(q=>q!==p&&q.x===nx&&q.y===ny)){p.fromX=p.x;p.fromY=p.y;p.x=nx;p.y=ny;p.dir=dest.dir;p.progress=0;}else p.progress=1;alive.push(p);}s.particles=alive;}
