import {elements,recipes,dirs,key,fresh,price,place,remove,tick} from './engine.js';
const $=s=>document.querySelector(s);let state;try{const saved=JSON.parse(localStorage.getItem('jagace-v1'));state=saved?.blocks&&saved?.unlocked?saved:fresh();}catch{state=fresh();}
let tab='build',selection=null,direction=0,factoryRecipe='lava',paused=false,speed=1,zoom=1,hover=null,erase=false;const canvas=$('#game'),ctx=canvas.getContext('2d');let cell=49,ox=0,oy=0,W=0,H=0;const COLS=12,ROWS=9;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function shop(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#discovered').textContent=`${state.unlocked.length}/10`;if(tab==='elements'){$('#shop-content').innerHTML='<div class="shop-label">YOUR ELEMENT COLLECTION</div>'+Object.entries(elements).map(([id,e])=>`<div class="element-entry"><span class="icon" style="background:${e.bg};color:${e.color}">${state.unlocked.includes(id)?e.icon:'♙'}</span><div><b>${e.name}</b><small>${state.unlocked.includes(id)?`◈ ${e.value} per element · ${e.interval}s production`:'Build its factory to unlock'}</small></div></div>`).join('');return;}
function item(type,el,name,icon,bg,color,desc){const cost=price(type,el);const selected=selection?.type===type&&selection?.el===el;return `<button class="shop-item ${selected?'selected':''}" data-type="${type}" data-el="${el||''}" ${type==='producer'&&!state.unlocked.includes(el)?'disabled':''}><span class="icon" style="background:${bg};color:${color}">${icon}</span><span class="item-text"><b>${name}</b><small>${desc}</small></span><span class="price">◈ ${cost}</span></button>`;}
$('#shop-content').innerHTML='<div class="shop-label">PRODUCTION</div>'+Object.entries(elements).filter(([id])=>state.unlocked.includes(id)||id==='lava').map(([id,e])=>item('producer',id,e.name+' producer',e.icon,e.bg,e.color,`1 ${e.name.toLowerCase()} every ${e.interval}s`)).join('')+'<div class="shop-divider"></div><div class="shop-label">COMBINE & CONNECT</div>'+item('factory',factoryRecipe,'Factory','▥','#e4e8d9','#6b8055','Two elements. Something new.')+`<select class="factory-choice" id="factory-recipe" aria-label="Factory recipe">${Object.entries(recipes).map(([id,inputs])=>`<option value="${id}" ${factoryRecipe===id?'selected':''}>${inputs.map(i=>elements[i].name).join(' + ')} → ${elements[id].name}</option>`).join('')}</select>`+item('belt',null,'Conveyor belt','⇢','#e7e9e2','#78826e','Keep your elements moving')+item('seller',null,'Selling block','◈','#f1e8c9','#ab9351','Turn any element into money');
$('#shop-content').querySelectorAll('.shop-item').forEach(b=>b.onclick=()=>{erase=false;selection={type:b.dataset.type,el:b.dataset.el||null};shop();updateHint()});$('#factory-recipe').onchange=e=>{factoryRecipe=e.target.value;if(selection?.type==='factory')selection.el=factoryRecipe;shop();updateHint()};}
function updateHint(){const name=erase?'Remove blocks':selection?(selection.type==='producer'?elements[selection.el].name+' producer':selection.type==='factory'?elements[selection.el].name+' factory':selection.type==='belt'?'Conveyor belt':'Selling block'):null;$('#selection-text').innerHTML=name?`<i class="key">↖</i> ${name} · ${erase?'50% refund':`output ${['right','down','left','up'][direction]}`}`:'<i class="key">↖</i> Select a block to start building';$('#placement-hint').textContent=erase?'Click a block to remove it':selection?'Click an empty tile to place · R to rotate':'A few elements. A world of possibilities.';canvas.style.cursor=selection||erase?'crosshair':'default';}
function stats(){$('#money').textContent=Math.floor(state.money).toLocaleString();$('#sold-count').textContent=state.sold.toLocaleString();$('#total-earned').textContent=state.earned.toLocaleString();$('#block-count').textContent=Object.keys(state.blocks).length;$('#rate').textContent=Math.round(state.earned/Math.max(state.clock,1)*60).toLocaleString();}
function resize(){const r=canvas.parentElement.getBoundingClientRect();W=r.width;H=r.height;canvas.width=W*devicePixelRatio;canvas.height=H*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);cell=Math.min((W-55)/COLS,(H-100)/ROWS)*zoom;ox=(W-COLS*cell)/2;oy=(H-ROWS*cell)/2+8;}
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function arrow(x,y,dir,color,size=8){ctx.save();ctx.translate(x,y);ctx.rotate(dir*Math.PI/2);ctx.strokeStyle=color;ctx.lineWidth=1.6;ctx.beginPath();ctx.moveTo(-size,0);ctx.lineTo(size,0);ctx.moveTo(size-4,-4);ctx.lineTo(size,0);ctx.lineTo(size-4,4);ctx.stroke();ctx.restore();}
function drawBlock(b,ghost=false){const x=ox+b.x*cell,y=oy+b.y*cell,sz=cell-7;ctx.globalAlpha=ghost?.48:1;const e=elements[b.el];let bg=b.type==='producer'?e.bg:b.type==='factory'?'#dce4cc':b.type==='seller'?'#eee1b3':'#d9dfcf';let border=b.type==='producer'?e.color+'77':b.type==='factory'?'#93a47c':b.type==='seller'?'#bdab73':'#b6c0a5';rounded(x+4,y+7,sz,sz,6,'#a4ae9222');rounded(x+3,y+3,sz,sz,6,bg,border);if(b.type==='belt'){ctx.save();ctx.beginPath();ctx.rect(x+7,y+7,cell-15,cell-15);ctx.clip();for(let i=-2;i<4;i++){const t=((state.clock*.65)%1+i)*cell/3;const cx=x+cell/2+(b.dir===0?t-cell/2:b.dir===2?cell/2-t:0);const cy=y+cell/2+(b.dir===1?t-cell/2:b.dir===3?cell/2-t:0);arrow(cx,cy,b.dir,'#9da98b',5);}ctx.restore();}else{ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${cell*.45}px "DM Sans", sans-serif`;ctx.fillStyle=b.type==='producer'?e.color:b.type==='factory'?'#6a8150':'#a48d47';ctx.fillText(b.type==='producer'?e.icon:b.type==='factory'?'▥':'◈',x+cell/2,y+cell*.43);if(b.type!=='seller'){arrow(x+cell*.7,y+cell*.77,b.dir,'#83926b',4);ctx.font=`${Math.max(6,cell*.14)}px sans-serif`;ctx.fillStyle='#73815f';if(cell>=35)ctx.fillText(b.type==='factory'?e.name.toUpperCase():'SOURCE',x+cell*.39,y+cell*.77);}else{ctx.font=`${Math.max(6,cell*.14)}px sans-serif`;if(cell>=35)ctx.fillText('SELL',x+cell*.5,y+cell*.77);}}
ctx.globalAlpha=1;}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#bfc7b044';for(let x=0;x<=COLS;x++)for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.arc(ox+x*cell,oy+y*cell,1.3,0,Math.PI*2);ctx.fill();}ctx.strokeStyle='#c8d0b64f';ctx.setLineDash([4,5]);ctx.strokeRect(ox-7,oy-7,COLS*cell+14,ROWS*cell+14);ctx.setLineDash([]);
Object.values(state.blocks).forEach(b=>drawBlock(b));for(const p of state.particles){const progress=Math.min(1,p.progress);const x=ox+(p.fromX+(p.x-p.fromX)*progress+.5)*cell,y=oy+(p.fromY+(p.y-p.fromY)*progress+.5)*cell;const e=elements[p.el];ctx.beginPath();ctx.arc(x,y,cell*.13,0,Math.PI*2);ctx.fillStyle=e.color;ctx.shadowColor='#4f573344';ctx.shadowBlur=4;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#fff8df';ctx.lineWidth=1.5;ctx.stroke();}
if(hover&&hover.x>=0&&hover.x<COLS&&hover.y>=0&&hover.y<ROWS){const b=state.blocks[key(hover.x,hover.y)];if(selection&&!b)drawBlock({...hover,...selection,dir:direction},true);ctx.strokeStyle=erase?'#c98568':'#8a9d73';ctx.lineWidth=2;ctx.strokeRect(ox+hover.x*cell+1,oy+hover.y*cell+1,cell-3,cell-3);if(b){const desc=b.type==='factory'?`${elements[b.el].name} · ${recipes[b.el].map(e=>`${elements[e].name}: ${b.stock[e]||0}`).join(' / ')}`:b.type==='producer'?`${elements[b.el].name} · every ${elements[b.el].interval}s`:b.type==='seller'?'Sells every element':'Conveyor · '+['right','down','left','up'][b.dir];ctx.font='10px sans-serif';const width=ctx.measureText(desc).width+22;const tx=Math.max(4,Math.min(W-width-4,ox+hover.x*cell));const ty=Math.max(48,oy+hover.y*cell-31);rounded(tx,ty,width,24,5,'#fbfaf3','#d4dac5');ctx.fillStyle='#637454';ctx.textAlign='left';ctx.fillText(desc,tx+11,ty+16);}}}
canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();hover={x:Math.floor((e.clientX-r.left-ox)/cell),y:Math.floor((e.clientY-r.top-oy)/cell)}};canvas.onpointerleave=()=>hover=null;
canvas.onpointerdown=e=>{canvas.onpointermove(e);if(!hover||hover.x<0||hover.y<0||hover.x>=COLS||hover.y>=ROWS)return;const {x,y}=hover;const b=state.blocks[key(x,y)];if(erase||e.button===2){if(remove(state,x,y)){toast('Block removed. 50% refunded.');stats();save();}return;}if(selection){const err=place(state,x,y,selection.type,selection.el,direction);if(err)toast(err);else{if(selection.type==='factory'){toast(`${elements[selection.el].name} producer unlocked!`);shop();}stats();save();}}else if(b){direction=(b.dir+1)%4;b.dir=direction;toast('Output rotated '+['right','down','left','up'][direction]);save();}};canvas.oncontextmenu=e=>e.preventDefault();
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;shop()});document.onkeydown=e=>{if(e.target.matches('select,input,button'))return;if(e.key.toLowerCase()==='r'){direction=(direction+1)%4;updateHint()}if(e.key==='Escape'){selection=null;erase=false;shop();updateHint()}if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();erase=!erase;selection=null;shop();updateHint()}if(e.code==='Space'){e.preventDefault();$('#pause').click()}};
$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'▶':'Ⅱ';$('#pause').title=paused?'Resume simulation':'Pause simulation'};$('#speed').onclick=()=>{speed=speed===1?2:speed===2?4:1;$('#speed').textContent=speed+'×'};$('#center').onclick=()=>{selection=null;erase=false;zoom=1;$('#zoom-label').textContent='100%';resize();shop();updateHint()};function setZoom(d){zoom=Math.max(.65,Math.min(1.35,zoom+d));$('#zoom-label').textContent=Math.round(zoom*100)+'%';resize()}$('#zoom-in').onclick=()=>setZoom(.1);$('#zoom-out').onclick=()=>setZoom(-.1);
const modal=$('#modal');$('#close-modal').onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal)modal.close()};$('#help').onclick=()=>{$('#modal-content').innerHTML='<div class="eyebrow">WELCOME TO THE ELEMENT FACTORY</div><h2>Make a little. Make more.</h2><p>Your starter line combines Earth + Fire into Lava, then sells it. You have ◈ 850 to expand.</p><ol><li>Choose a producer or building, then click an empty tile. Blocks output in the arrow direction.</li><li>Place conveyors between producers, factories, and selling blocks. Press <b>R</b> to rotate before placing, or click an existing block with nothing selected to rotate it.</li><li>Choose a recipe below Factory before placing it. Feed both ingredients into adjacent sides; its output follows its arrow.</li><li>Building a factory unlocks a producer for that element. Advanced producers cost more and drop less often.</li><li>Generic selling blocks accept every element. Press Backspace for removal mode (50% refund), Escape to deselect, or Space to pause.</li></ol><p>Your factory saves automatically in this browser. Keep experimenting — there’s no finish line.</p>';modal.showModal()};
$('#recipes-button').onclick=()=>{$('#modal-content').innerHTML='<div class="eyebrow">THE DISCOVERY NOTEBOOK</div><h2>Something new, from two.</h2><p>Every factory costs ◈ 150. Place one to unlock its producer.</p>'+Object.entries(recipes).map(([el,inputs])=>`<div class="recipe-row"><span>${inputs.map(i=>elements[i].icon+' '+elements[i].name).join(' + ')} → <b>${elements[el].name}</b><br><small>Sell for ◈ ${elements[el].value} · Producer ◈ ${elements[el].cost}</small></span><button data-recipe="${el}">Build ↗</button></div>`).join('');modal.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>{factoryRecipe=b.dataset.recipe;selection={type:'factory',el:factoryRecipe};erase=false;tab='build';shop();updateHint();modal.close()});modal.showModal()};$('#reset').onclick=()=>{$('#modal-content').innerHTML='<h2>A fresh beginning?</h2><p>This will reset your factory, discoveries, and earnings to the starter layout.</p><button id="confirm-reset" class="factory-choice">Reset factory</button>';$('#confirm-reset').onclick=()=>{state=fresh();selection=null;erase=false;shop();stats();updateHint();save();modal.close();toast('A new factory. Endless possibilities.')};modal.showModal()};
function save(){try{localStorage.setItem('jagace-v1',JSON.stringify(state))}catch{toast('Browser storage unavailable. Keep this tab open to retain progress.')}}window.addEventListener('beforeunload',save);setInterval(save,4000);let last=performance.now(),ui=0;function frame(now){let dt=Math.min((now-last)/1000,.1);last=now;if(!paused){let remaining=dt*speed;while(remaining>0){const step=Math.min(remaining,.05);tick(state,step);remaining-=step;}}ui+=dt;if(ui>.25){stats();ui=0;}draw();requestAnimationFrame(frame)}new ResizeObserver(resize).observe(canvas.parentElement);shop();stats();updateHint();resize();requestAnimationFrame(frame);
